---
# https://taskfile.dev

version: "3"

vars:
  PKG_NAME: github.com/comunidade-shallom/peristera
  APP_BASE_NAME: datasync
  DIR_DIST: ./bin
  BUILD_DATE: '{{now | date "2006-01-02T15:04:05"}}'
  APP_VERSION:
    sh: git describe --dirty --always --tags
  GIT_HASH:
    sh: git log -n 1 --format=%h | echo "unknow"

dotenv: [".env"]

tasks:
  format:
    desc: Check source code
    cmds:
      - go fmt ./...

  vet:
    desc: Check source code
    cmds:
      - go vet ./...

  check:
    desc: Check source code
    deps:
      - format
      - vet
    cmds:
      - golangci-lint run ./... {{.CLI_ARGS}}

  clean:
    desc: Remove old binaries
    cmds:
      - rm -rf {{.DIR_DIST}}/{{.APP_BASE_NAME}}-*

  install:
    desc: Install dependencies
    cmds:
      - go get ./...
      - go mod vendor
      - go mod tidy

  install:lint:
    desc: Install dependencies
    status:
      - test -f $(go env GOPATH)/bin/golangci-lint
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

  install:gofumpt:
    desc: Install dependencies
    status:
      - test -f $(go env GOPATH)/bin/gofumpt
    cmds:
      - go install mvdan.cc/gofumpt@latest

  setup:
    desc: Setup project dependencies
    deps:
      - install
      - install:lint
      - install:gofumpt

  build:
    desc: Build CLI (linux by default)
    cmds:
      - echo "Generating {{.BIN_NAME}}"
      - "{{.EXTRA_ENVS}} go build {{.BUILDFLAGS}} {{.LDFLAGS}} -o {{.DIR_DIST}}/{{.BIN_NAME}} ./apps/{{.APP}}"
      - chmod +x {{.DIR_DIST}}/{{.BIN_NAME}}
    vars:
      LDFLAGS: -ldflags "-X {{.PKG_NAME}}/pkg/config.commit={{.GIT_HASH}} -X {{.PKG_NAME}}/pkg/config.version={{.APP_VERSION}} -X {{.PKG_NAME}}/pkg/config.buildDate={{.BUILD_DATE}}"
      APP: '{{default "cli" .APP}}'
      GOOS: '{{default "linux" .GOOS}}'
      GOARCH: '{{default "amd64" .GOARCH}}'
      CGO_ENABLED: "{{default 0 .CGO_ENABLED}}"
      BIN_NAME: "{{.APP_BASE_NAME}}-{{.APP}}-{{.GOOS}}-{{.GOARCH}}"
    env:
      GOOS: "{{.GOOS}}"
      GOARCH: "{{.GOARCH}}"
      GOARM: "{{.GOARM}}"
      CGO_ENABLED: "{{.CGO_ENABLED}}"

  build:cli:
    desc: Build CLI
    cmds:
      - task: build
        vars:
          APP: cli
          GOOS:
            sh: "go env GOHOSTOS"
          GOARCH:
            sh: "go env GOARCH"

  run:
    cmds:
      - go run apps/cli/main.go {{.CLI_ARGS}}
    silent: true

  copy:
    desc: Copy CLI to servers in Fundimisa and Elyte
    cmds:
      - task build
      - scp bin/datasync-cli-linux-amd64 root@10.10.0.2:/app/datasync/datasync
      - scp bin/datasync-cli-linux-amd64 root@10.0.0.10:/app/datasync/datasync
